<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Identity\Modules.Identity\Modules.Identity.csproj" />
    <ProjectReference Include="..\Modules.Quiz.Application\Modules.Quiz.Application.csproj" />
    <ProjectReference Include="..\Modules.Quiz.Infrastructure\Modules.Quiz.Infrastructure.csproj" />
  </ItemGroup>
</Project>